export const infoArr = [
	{
		company: "Bulk2Save",
		role: "Full Stack Developer",
		startEnd: "2023 to Present",
		description: `Architected a turn key e-commerce platform so that clients could browse and order from the catalog online, freeing the sales team to focus on building relationships and closing deals.`,
		companyBio: "provides an extensive array of products to businesses and individuals at wholesale prices.",
		logoSrc: "https://picsum.photos/100",
		url: "https://www.bulk2save.com",
	},
	{
		company: "DirtE-Bikes",
		role: "Full Stack Developer",
		startEnd: "2023",
		description: "Created a custom designed storefront for E-bikes, focusing on the customizability of the bikes, from motor to battery to suspension, etc.",
		companyBio: "crafts electric dirt bikes for off-road use, custom assembled to fit individual needs.",
		logoSrc: "https://picsum.photos/100",
		url: "https://www.dirt-e-bikes.com",
	},
	{
		company: "Maxie Paper",
		role: "Front End Developer",
		startEnd: "2022-2023",
		description: "Designed and developed an animated “Scrollytelling“ website, keeping visitors visually engaged while highlighting product info, creating a more interactive and engaging experience.",
		companyBio: "supplies a wide range of paper products to businesses and retailers.",
		logoSrc: "https://picsum.photos/100",
		url: "https://www.maxiepaper.com",
	},
	{
		company: "Knaq App",
		role: "Front End Developer",
		startEnd: "2021-2022",
		description: "Built a social media platform for users to upload, share, and interact with media content, voice chat, and make donations via web3",
		companyBio: "is a Web3 layer that supercharges your favorite social media platforms!",
		logoSrc: "https://picsum.photos/100",
		url: "https://www.knaqapp.com",
	},
	{
		company: "Coast Airbrush",
		role: "Full Stack Developer",
		startEnd: "2021-2022",
		description:
			"Reengineered an old website to use Clover Checkout and Inventory APIs so that both online and in-store purchases would be handled by Clover, keeping all sales and inventory data in one place",
		companyBio: "is the largest airbrush supplier in the world. Coast Airbrush is your source for all of your airbrush needs.",
		logoSrc: "https://picsum.photos/100",
		url: "https://www.coastairbrush.com/",
	},
	{
		company: "Paradise Found SB",
		role: "Automation Engineer",
		startEnd: "2021",
		description: "Synchronized the inventory of a Webflow store with the physical store’s desktop inventory system, ensuring the correct stock levels were displayed online",
		companyBio: "has everything for your eclectic needs from our curated book selection to healing crystals to intuitive readings!",
		logoSrc: "https://picsum.photos/100",
		url: "https://www.coastairbrush.com/",
	},
	{
		company: "Rockwell Collins",
		role: "Systems Engineer",
		startEnd: "2018-2019",
		description: "Captured comprehensive hardware and software requirements for the private jet cabins, ensuring that the system would meet the needs of the end users",
		companyBio: "is a multinational corporation providing avionics and information technology systems",
		logoSrc: "https://picsum.photos/100",
		url: "https://www.coastairbrush.com/",
	},
]
